#!/bin/bash

cp /etc/nixos/nixos/hardware-configuration.nix ./nixos/hardware-configuration.nix # Copy existing hardware config generated by installation

sudo mv /etc/nixos /etc/nixos.bak  # Backup the original configuration
sudo ln -s ./ /etc/nixos # Create symlink for root in nixos folder

sudo nixos-rebuild switch # Deploy
reboot # Reboot to refresh environment
